#Boris Skurikhin
#1007339
#Assignment 1 - Module 1

CC = gcc
CFLAGSPARSER = -Wall -ansi -pedantic -std=c11 -Iinclude/

all: list parser

parser: src/CalendarParser.c
	$(CC) $(CFLAGSPARSER) src/CalendarParser.c -o bin/parser.out

list:

clean:
	
